name: Release & Merge

on:
  push:
    branches:
      - '**'
      - '!release'

jobs:
  Release:
    runs-on: ubuntu-latest
    
    steps:
      - name: clone
        run: |
          pwd
          echo '创建 tree/：'
          mkdir tree
          echo '克隆 三个分支：'
          git clone https://github.com/PJ-568/568tools.git -b assets /home/runner/tree/assets
          git clone https://github.com/PJ-568/568tools.git -b main /home/runner/tree/main
          echo '检查 tree/assets：'
          ls /home/runner/tree/assets
          echo '检查 tree/main：'
          ls /home/runner/tree/main
      
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release

      - name: merge
        run: |
          echo '清空 release：'
          rm -r ./*
          echo '检查 release：'
          ls
          echo '复制 tree/assets/* 到 release/：'
          cp -v -u -r /home/runner/tree/assets/* .
          echo '复制 tree/main/* 到 tree/release/：'
          cp -v -u -r /home/runner/tree/main/* .

      - name: push
        run: |
          git config --global user.name "PJ569-bot"
          git config --global user.email "LiuTian-PJ568@PJ568.eu.org"
          git add -A
          git commit -m '自动 Release'
          git push