name: Release

on:
  push:
    branches:
      - '**'
      - '!release'

jobs:
  Release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone
        run: |
          echo '创建 tree/：'
          mkdir /home/runner/tree
          echo '克隆 三个分支：'
          git clone https://github.com/PJ-568/568tools.git -b assets /home/runner/tree/assets
          echo '检查 tree/assets：'
          ls /home/runner/tree/assets
      
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: recursive

      - name: Merge
        run: |
          echo '复制 tree/assets/* 到 .：'
          cp -v -u -r /home/runner/tree/assets/* .
          rm -r ./lib/
          git rm --cached lib
          
      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:2.0.0
        with:
          add_suffix: false     # Optional

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://tools.pj568.eu.org/

      - name: Output sitemap stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      # Deploy
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: release # The branch the action should deploy to.
          folder: . # The folder the action should deploy.

      # - name: Checkout release branch
      #   uses: actions/checkout@v3
      #   with:
      #     ref: release

      # - name: Update tool lib
      #   run: |
      #     rm -r ./lib/
      #     git config --global user.name "PJ569-bot"
      #     git config --global user.email "LiuTian-PJ568@PJ568.eu.org"
      #     git submodule update
      #     # git rm --cached lib
      #     # git submodule add -b tools https://github.com/PJ-568/568tools.git ./lib
      #     # git add ./lib/
      #     git commit -m '库更新'
      #     git push

      - name: Ping Google
        run: curl https://www.google.com/ping?sitemap=https://Tools.PJ568.eu.org/sitemap.xml